chivstats/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings

urlpatterns = [
    path('leaderboards/', include('leaderboards.urls')),
    path('admin/', admin.site.urls),
    path("account/", include("account.urls")),
    path('', RedirectView.as_view(url='/leaderboards/', permanent=True)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),  # changed url to path
    ] + urlpatterns

leaderboards/urls.py
from django.urls import path
from . import views
from .views import PlayerListAPIView, LatestLeaderboardListAPIView, LeaderboardListAPIView, get_leaderboard

app_name = 'leaderboards'

urlpatterns = [
    path('', views.index, name='index'),
    path('player_search/', views.player_search, name='player_search'),
    path('ranked_combat/', views.ranked_combat_leaderboard, name='ranked_combat_leaderboard'),
    path('ranked_matches/', views.ranked_matches, name='ranked_matches'),
    path('about_elo/', views.about_elo, name='about_elo'),
    path('xp-ratio-scatter/', views.xp_ratio_scatter, name='xp_ratio_scatter'),
    path('meta_sumstats/', views.get_meta_sumstats, name='meta_sumstats'),
    path('top_players/', views.top_players_by_playtime, name='top_players'),
    path('player_progress/', views.player_progress_over_time, name='player_progress'),
    path('peasant-caps/', views.peasant_caps_leaderboard, name='peasant_caps_leaderboard'),
    path('wealth/', views.wealth_leaderboard, name='wealth_leaderboard'),
    path('top_gainers/', views.top_gainers_leaderboard, name='top_gainers_leaderboard'),
    path('merged_leaderboard_view/', views.merged_leaderboard_view, name='merged_leaderboard_view'),
    path('show_games/', views.show_games, name='show_games'),
    path('go_touch_grass/', views.go_touch_grass_leaderboard, name='go_touch_grass_leaderboard'),
    path('player/<str:playfabid>/', views.player_profile, name='player_profile'),
    path('tattle/', views.tattle, name='tattle'),
    path('api/players/', PlayerListAPIView.as_view(), name='player-list-api'),
    path('api/latest-leaderboards/', LatestLeaderboardListAPIView.as_view(), name='latest-leaderboards'),
    path('api/leaderboards/', LeaderboardListAPIView.as_view(), name='leaderboards-api'),
    path('api/get_leaderboard/', views.get_leaderboard, name='get_leaderboard'),
    path('hourly_player_count/', views.get_hourly_player_count, name='hourly_player_count'),
    path('api/hourly-player-count/', views.get_hourly_player_count, name='api_hourly_player_count'),
    path('daily_unique_accounts/', views.get_daily_unique_accounts, name='daily_unique_accounts'),
    path('api/daily-unique-accounts/', views.get_daily_unique_accounts, name='api_daily_unique_accounts'),
    path('<str:leaderboard_name>/', views.leaderboard, name='leaderboard'),
]

leaderboards/views.py
import re, json
from copy import copy
from datetime import datetime, timedelta
from collections import defaultdict
from django.utils.dateformat import DateFormat
from django.apps import apps
from django.core.paginator import Paginator
from django.core.cache import cache
from django.db import connection
from django.db.models import Avg, Max, Sum, Q, F, Subquery, OuterRef
from django.http import Http404, JsonResponse, HttpResponseBadRequest
from django.shortcuts import redirect, render
from django.views.decorators.cache import cache_page

from django.db.models import Case, When, Value, FloatField, Window, F, ExpressionWrapper
from django.db.models.functions import Rank

from rest_framework import generics, status
from rest_framework.decorators import api_view
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response

from leaderboards import models
from .models import (
    Leaderboard, Player, PlaytimeEx, GlobalXp, HourlyPlayerCount, ChivstatsSumstats, DailyPlaytime, leaderboard_classes, LatestLeaderboard, RankedPlayer,
    DuoTeam, Duel)
from .serializers import (LatestLeaderboardSerializer, PlayerSerializer)
from .serializers import LeaderboardSerializer
from .utils import (humanize_leaderboard_name, organize_sidebar, create_leaderboard_list, read_yaml_news, to_json, get_level_data)

from geoip2.database import Reader
from geoip2.errors import AddressNotFoundError, GeoIP2Error

leaderboards = copy(leaderboard_classes);
leaderboards.sort(key=organize_sidebar);
leaderboard_list_of_dict = create_leaderboard_list()

def calculate_level_and_gold(xp):
    level_data = get_level_data()
    level = 0
    total_gold = 0
    for level_info in level_data:
        if xp >= level_info['xp']:
            level = level_info['level']
            total_gold += level_info['reward']
        else:
            break
    return level, total_gold

def xp_ratio_scatter(request):
    context = {
        'leaderboards': leaderboard_list_of_dict,
    }

    return render(request, 'leaderboards/xp_ratio_scatter.html', context)


def peasant_caps_leaderboard(request):
    players_with_caps = Player.objects.filter(peasant_cap=True).order_by('peasant_cap_date')
    
    # Add last_seen_formatted field
    for player in players_with_caps:
        if player.lastseen_serial:
            # Convert the serial number to a date string
            last_seen_formatted = datetime.strptime(str(player.lastseen_serial)[:8], '%Y%m%d').strftime('%Y-%m-%d')
            player.last_seen_formatted = last_seen_formatted
        else:
            player.last_seen_formatted = 'Never'

    context = {
        'players': players_with_caps,
        'leaderboards': leaderboard_list_of_dict,
    }
    return render(request, 'leaderboards/peasant_caps_leaderboard.html', context)

from django.core.paginator import Paginator


def about_elo(request):
    # Add any dynamic content to the context as needed, for now it's empty.
    context = {}
    return render(request, 'leaderboards/about_elo.html', context)

def wealth_leaderboard(request):
    wealth_type = request.GET.get('wealth_type', 'gold')  # Default to 'gold' if not specified
    page = request.GET.get('page', 1)

    if wealth_type == 'gold':
        players_query = Player.objects.all().order_by('-gd')
    else:  # Default to Crowns if wealth_type is not 'gold'
        players_query = Player.objects.all().order_by('-cr')

    paginator = Paginator(players_query, 50)  # Show 50 players per page
    players = paginator.get_page(page)

    start_index = players.start_index()  # Get the start index for the current page

    # Add 'wealth' and 'rank' attributes to each player object
    for index, player in enumerate(players, start=start_index):
        player.wealth = player.gd if wealth_type == 'gold' else player.cr
        player.rank = index

    context = {
        'players': players,
        'wealth_type': wealth_type,
        'leaderboards': leaderboard_list_of_dict,
    }
    return render(request, 'leaderboards/wealth_leaderboard.html', context)

def ranked_combat_leaderboard(request):
    page = request.GET.get('page', 1)
    ranked_players_list = RankedPlayer.objects.all().order_by('-elo_duelsx')  # Updated field name here
    
    # Debugging: Check if the query set returns any results
    print('Ranked Players List:', ranked_players_list)

    paginator = Paginator(ranked_players_list, 50)  # Adjust the number per page as needed
    ranked_players_page = paginator.get_page(page)

    playfabids = [ranked_player.playfabid for ranked_player in ranked_players_page]
    players = Player.objects.filter(playfabid__in=playfabids).in_bulk(field_name='playfabid')

    players_data = []
    for ranked_player in ranked_players_page:
        # Get the related Player object from the pre-fetched players dictionary
        player = players.get(ranked_player.playfabid)
        
        # Determine the display name using the order of precedence you've given
        display_name = ranked_player.gamename or ranked_player.common_name or (player.most_common_alias() if player else None)
        
        # Round the elo_duelsx value to the nearest whole number
        elo_rating_rounded = round(ranked_player.elo_duelsx)
        
        # Append the player data with the chosen display name and the rounded ELO rating
        players_data.append({
            'playfabid': ranked_player.playfabid,
            'common_name': display_name,
            'elo_rating': elo_rating_rounded,  # Use the rounded value here
            'matches': ranked_player.matches,
            'kills': ranked_player.kills,
            'deaths': ranked_player.deaths
        })

    # New code for fetching and processing DuoTeam data
    duo_teams_list = DuoTeam.objects.filter(retired=False).order_by('-elo_rating')  # Adjust the filter and order as needed
    duo_paginator = Paginator(duo_teams_list, 10)  # Adjust the number per page as needed
    page_duo = request.GET.get('page_duo', 1)
    duo_teams_page = duo_paginator.get_page(page_duo)

    duo_teams_data = []
    for team in duo_teams_page:
        try:
            player1 = RankedPlayer.objects.get(playfabid=team.player1_id)
            player2 = RankedPlayer.objects.get(playfabid=team.player2_id)
            team_data = {
                'team_name': team.team_name or f"{player1.common_name} & {player2.common_name}",
                'elo_rating': team.elo_rating,
                'matches_played': team.matches_played,
                'player1_name': player1.common_name,
                'player2_name': player2.common_name
            }
            duo_teams_data.append(team_data)
        except RankedPlayer.DoesNotExist:
            # Handle the case where one of the players does not exist
            # For example, skip this team or add a placeholder
            continue


    context = {
        'duo_teams_data': duo_teams_data,
        'duo_teams_page': duo_teams_page,
        'players_data': players_data,  # Make sure this matches the template variable
        'ranked_players_page': ranked_players_page,  # Add this to the context
        'leaderboards': leaderboard_list_of_dict,
    }

    return render(request, 'leaderboards/ranked_combat_leaderboard.html', context)

def ranked_matches(request):
    # Fetch top 20 players based on ELO
    top_players = RankedPlayer.objects.order_by('-elo_duelsx')[:20]

    # Initialize dictionary for ELO histories
    elo_histories = {}

    # Loop through each top player and fetch their duel history
    for player in top_players:
        player_duels = Duel.objects.filter(
            Q(winner_playfabid=player.playfabid) | Q(loser_playfabid=player.playfabid)
        ).order_by('timestamp').values('timestamp', 'winner_playfabid', 'winner_elo', 'loser_playfabid', 'loser_elo')

        elo_history = []
        for duel in player_duels:
            timestamp_formatted = DateFormat(duel['timestamp']).format('c')  # ISO format
            if duel['winner_playfabid'] == player.playfabid:
                elo_history.append({'timestamp': timestamp_formatted, 'elo': duel['winner_elo']})
            elif duel['loser_playfabid'] == player.playfabid:
                elo_history.append({'timestamp': timestamp_formatted, 'elo': duel['loser_elo']})

        elo_histories[player.playfabid] = elo_history

    # Prepare match history data
    match_history_data = Duel.objects.all().order_by('-timestamp')
    playfabids = set([match.winner_playfabid for match in match_history_data] + 
                     [match.loser_playfabid for match in match_history_data])
    players = Player.objects.filter(playfabid__in=playfabids).in_bulk(field_name='playfabid')

    enhanced_match_data = []
    for match in match_history_data:
        winner_player = players.get(match.winner_playfabid)
        loser_player = players.get(match.loser_playfabid)
        enhanced_match = {
            'timestamp': match.timestamp,
            'winner_name': winner_player.most_common_alias() if winner_player else match.winner_playfabid,
            'winner_score': match.winner_score,
            'loser_name': loser_player.most_common_alias() if loser_player else match.loser_playfabid,
            'loser_score': match.loser_score,
            'winner_url': f'/leaderboards/player/{match.winner_playfabid}',
            'loser_url': f'/leaderboards/player/{match.loser_playfabid}'
        }
        enhanced_match_data.append(enhanced_match)

    # Convert elo_histories to JSON
    elo_histories_json = json.dumps(elo_histories)

    context = {
        'match_history_data': enhanced_match_data,
        'elo_histories_json': elo_histories_json,  # Pass the JSON string
        'leaderboards': leaderboard_list_of_dict,
    }

    return render(request, 'leaderboards/ranked_matches.html', context)




def player_progress_over_time(request, source_table='GlobalXp'):

leaderboards/templates/leaderboards/go_touch_grass.html
{% extends 'leaderboards/base.html' %}
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-EQG3BMRF63"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-EQG3BMRF63');
</script>

{% block content %}
<h1>{{ leaderboard_name }}</h1>
<br>
<p>Latest update: {{ latest_update|date:"F j, Y, P T" }}</p>
<br>

<!-- Search form -->
<form method="GET" action="{% url 'leaderboards:leaderboard' leaderboard_name %}">
    <div class="input-group mb-3">
        <input type="text" class="form-control custom-input" name="search_query" placeholder="Enter player name" value="{{ search_query }}">
        <div class="input-group-append">
            <button class="btn btn-outline-primary" type="submit">Search</button>
        </div>
    </div>
</form>

<br>
{% if search_query and player_position %}
    <p>Your position: {{ player_position }}</p>
{% endif %}
<br>

<!-- Pagination at the top -->
<div class="d-flex justify-content-center">
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info" href="?page=1">First</a>
        <a class="btn btn-outline-info" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current-page d-inline-block h-100 pl-4 text-secondary"> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
    {% if page_obj.has_next %}
        <a class="btn btn-outline-info" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
</div>

<table class="table table-striped" id="leaderboardTable">
    <thead>
        <tr>
            <th>Position</th>
            <th>Display Name</th>
            <th>Stat Value</th>
            <th>Player ID</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in page_obj %}
            <tr>
                <td>
                    {% if search_query and player_position %}
                        {% if entry.rank == player_position %}
                            {{ player_position }}
                        {% else %}
                            {{ forloop.counter|add:page_obj.start_index|add:"-1" }}
                        {% endif %}
                    {% else %}
                        {{ forloop.counter|add:page_obj.start_index|add:"-1" }}
                    {% endif %}
                </td>
                <td class="displayName">{{ entry.playfabid.most_common_alias }}</td>
                <td>{{ entry.stat_value }}</td>
                <td>
                    <a href="{% url 'leaderboards:player_profile' entry.playfabid.playfabid %}">{{ entry.playfabid.playfabid }}</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Pagination at the bottom -->
<div class="d-flex justify-content-center">
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info" href="?page=1">First</a>
        <a class="btn btn-outline-info" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current-page d-inline-block h-100 pl-4 text-secondary"> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
    {% if page_obj.has_next %}
        <a class="btn btn-outline-info" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
</div>
{% endblock %}

leaderboards/templates/leaderboards/peasant_caps_leaderboard.html
{% extends "leaderboards/base.html" %}
{% block content %}
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-EQG3BMRF63"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-EQG3BMRF63');
</script>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Peasant Caps Leaderboard</title>
    <style>
        /* Custom styles can go here */
    </style>
</head>
<body>
    <div class="container">
        <h1>Peasant Caps Leaderboard</h1><br><img src="https://chivstats.xyz/static/peasantcaps.png"><br>
        <br>This was a one-time (80% complete) data gathering and will not be updated. Click on a column to sort by that column.<br>
        <table id="sortableTable" class="table">
            <thead>
                <tr>
                    <th id="Name" onclick="sortTable('sortableTable', 0)">Name <i class="bi bi-arrow-down-up"></i></th>
                    <th id="lastSeen" onclick="sortTable('sortableTable', 1)">Last Seen Playing <i class="bi bi-arrow-down-up"></i></th>
                    <th id="capDate" onclick="sortTable('sortableTable', 2)">Date Cap Awarded <i class="bi bi-arrow-down-up"></i></th>
                </tr>
            </thead>
            <tbody>
                {% for player in players %}
                    <tr>
                        <td>
                            <!-- Link to player profile -->
                            <a href="{% url 'leaderboards:player_profile' player.playfabid %}">
                                {{ player.most_common_alias }}
                            </a>
                        </td>
                        <td>{{ player.last_seen_formatted }}</td>
                        <td>{{ player.peasant_cap_date|date:"Y-m-d H:i" }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3">No players found.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

  <!-- Bootstrap Icons CDN -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">

  <!-- Bootstrap JS and its dependencies -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
    <!-- JavaScript Sorting Function -->
    <script>
        function sortTable(tableId, columnIndex) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById(tableId);
            switching = true;
            dir = "asc"; 

            // Code to switch icons based on direction
            var header = table.rows[0].getElementsByTagName("TH")[columnIndex];
            var icons = header.getElementsByTagName("I");
            if (icons.length > 0) {
                var icon = icons[0];
                if (dir === "asc") {
                    icon.className = "bi bi-arrow-down";
                } else {
                    icon.className = "bi bi-arrow-up";
                }
            }

            while (switching) {
            switching = false;
            rows = table.rows;

            for (i = 1; i < (rows.length - 1); i++) {
                shouldSwitch = false;
                x = rows[i].getElementsByTagName("TD")[columnIndex];
                y = rows[i + 1].getElementsByTagName("TD")[columnIndex];

                if (dir == "asc") {
                    if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                    }
                } else if (dir == "desc") {
                    if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                    }
                }
            }
            if (shouldSwitch) {
                rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                switching = true;
                switchcount ++;      
            } else {
                if (switchcount == 0 && dir == "asc") {
                    dir = "desc";
                    switching = true;
                }
            }
        }
    }
    </script>
</body>
</html>
{% endblock %}

leaderboards/templates/leaderboards/player_count.html
<h1>{{ collection_name }} Player Count Over Time</h1>
<table>
    <thead>
        <tr>
            <th>Serial</th>
            <th>Player Count</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in player_count_list %}
        <tr>
            <td>{{ entry.serial }}</td>
            <td>{{ entry.max_position }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

leaderboards/templates/leaderboards/search_playfabid.html
{% extends 'leaderboards/base.html' %}

{% block sidebar %}
<li class="nav-item">
    <span class="nav-link font-weight-bold">Leaderboards</span>
</li>
{% for leaderboard_name in leaderboards %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'leaderboards:leaderboard' leaderboard_name %}">{{ leaderboard_name }}</a>
    </li>
{% endfor %}
{% endblock %}
{% block content %}
  <h1>Search Player ID</h1>
  <br><br><br>
  <form method="get" action="{% url 'leaderboards:search_playfabid' %}">
    <label for="search_query">Player ID:</label>
    <input type="text" name="search_query" value="{{ search_query }}" required>
    <button type="submit">Search</button>
  </form>

  {% if search_query %}
    <h2>Results for: {{ search_query }}</h2>

    {% if playfab_data %}
    <table class="table table-striped search-results">
        <thead>
          <tr>
            <th>Collection</th>
            <th>Position</th>
            <th>Display Name</th>
            <th>Stat Value</th>
            <th>Player ID</th>
            <th>Total Stat Count</th> <!-- Added header -->
          </tr>
        </thead>
        <tbody>
          {% for entry in playfab_data %}
            <tr>
              <td>{{ entry.collection_name }}</td>
              <td>{{ entry.position|add:1 }}</td>
              <td>{{ entry.display_name }}</td>
              <td>{{ entry.stat_value }}</td>
              <td>{{ entry.playfab_id }}</td>
              <td>{{ entry.total_count }}</td> <!-- Added cell -->
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No results found.</p>
    {% endif %}
  {% endif %}
{% endblock %}

leaderboards/templates/leaderboards/sidebar.html
<!-- sidebar.html -->
<ul class="nav flex-column">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'leaderboards:index' %}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="https://discord.gg/chiv2unchained">Chivalry Unchained Discord</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'leaderboards:player_search' %}">Player Search</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'leaderboards:hourly_player_count' %}">Hourly Player Count</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'leaderboards:show_games' %}">Server List</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'leaderboards:top_gainers_leaderboard' %}">Meta: Top Gainers</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'leaderboards:player_progress' %}"><b>Meta: Graph Progress(XP)</b></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'leaderboards:ranked_combat_leaderboard' %}"><b>New: Ranked Combat</b></a>
    </li>
    {% for item in leaderboards %}
        {% if item.category == 'category' %}
            <li class="nav-item">
                <span class="nav-link font-weight-bold">Leaderboards {{ item.leaderboard }}</span>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'leaderboards:leaderboard' item.url %}">{{ item.leaderboard }}</a>
            </li>
        {% endif %}
    {% endfor %}
</ul>

leaderboards/templates/leaderboards/top_players.html
{% extends 'leaderboards/base.html' %}

{% block content %}
<h1>Top Players by Average Playtime</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Rank</th>
            <th>Playfab ID</th>
            <th>Common Alias</th>
            <th>Average Playtime</th>
        </tr>
    </thead>
    <tbody>
        {% for player in players %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ player.playfabid }}</td>
                <td>{{ player.most_common_alias }}</td>
                <td>{{ player.average_playtime }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

leaderboards/templates/leaderboards/wealth_leaderboard.html
{% extends 'leaderboards/base.html' %}
{% block content %}
<style>
    .rank-column {
        width: 50px;  /* Adjust the width as needed */
        text-align: center;
    }
</style>
<div class="container">
    <h1>Wealth Leaderboard</h1><br>This was a one-time data gathering and will not be updated. Click on a column to sort by that column.<br>
    <div>
        <form action="{% url 'leaderboards:wealth_leaderboard' %}" method="get">
            <input type="radio" id="gold" name="wealth_type" value="gold" {% if wealth_type == 'gold' %}checked{% endif %}>
            <label for="gold">Gold</label>
            <input type="radio" id="crowns" name="wealth_type" value="crowns" {% if wealth_type == 'crowns' %}checked{% endif %}>
            <label for="crowns">Crowns</label>
            <input type="submit" value="Filter">
        </form>
    </div>

    <h2>{{ wealth_type|title }} Leaderboard</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Position</th>
                <th>Name</th>
                <th>{{ wealth_type|title }}</th>
            </tr>
        </thead>
        <tbody>
            {% for player in players %}
                <tr>
                    <td class="rank-column">{{ player.rank }}</td>
                    <td><a href="{% url 'leaderboards:player_profile' player.playfabid %}">{{ player.most_common_alias }}</a></td>
                    <td>{{ player.wealth }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if players.has_previous %}
                <li class="page-item"><a class="page-link" href="?wealth_type={{ wealth_type }}&page=1">First</a></li>
                <li class="page-item"><a class="page-link" href="?wealth_type={{ wealth_type }}&page={{ players.previous_page_number }}">Previous</a></li>
            {% endif %}
            {% for num in players.paginator.page_range %}
                {% if num >= players.number|add:'-3' and num <= players.number|add:'3' %}
                    {% if players.number == num %}
                        <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?wealth_type={{ wealth_type }}&page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            {% if players.has_next %}
                <li class="page-item"><a class="page-link" href="?wealth_type={{ wealth_type }}&page={{ players.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?wealth_type={{ wealth_type }}&page={{ players.paginator.num_pages }}">Last</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}